### ISSUE TITLE
problem it only works when i restart it

### ISSUE THREAD

**Issue by killarabg** [cadburry6969/cad-chopshop#3]
I have the following problem on esx legacy when I start the script and go in the server by clicking on chopradio it says that the search is starting but nothing happens but when I restart the script while I'm inside it starts and works

**Comment by cadburry6969** [comment]
i think i had already fixed this
check https://github.com/cadburry6969/cad-chopshop/commit/c5c43a55da4fa0641ec8f1ed79362def7537e325
